
spring:
  cloud:
    admin:
     client:
       url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

message: "this is the demo message from the config server"       
